# Generated by Django 5.1.2 on 2024-10-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actor",
            old_name="nacionality",
            new_name="nationality",
        ),
    ]
